### ISSUE TITLE
Can not get comment from post of pages

### ISSUE THREAD

**Issue by tomrambo191** [fbsamples/live-comments-teleprompter#10]
Hi,
I can't get other comment from post of pages but I only can get my comment on post of pages.
So, can not see any other user comment from post of pages.
On personal's post fine!
what should I do?

Thank you.

**Comment by bradisbell** [comment]
Can you provide a link to the post that's giving you trouble?  Thanks.

**Comment by tomrambo191** [comment]
Hi,
For example this post.
https://www.facebook.com/sousprig/videos/1045121272249169

**Comment by bradisbell** [comment]
I am able to see the four comments for that video.

![Screenshot](https://user-images.githubusercontent.com/1097509/37790520-0a0cf8e2-2dc4-11e8-8060-4dc469860990.png)

Do you have any errors in your developer console?

**Comment by bradisbell** [comment]
Closing this issue for now.  Please comment if you are able to provide more information.
