### ISSUE TITLE
Cannot get this to run

### ISSUE THREAD

**Issue by fmerk353** [fbsamples/live-comments-teleprompter#12]
We installed and got this running. Sent a test message and it showed up. Sent a second one and got a note from FB locking us out till we posted a selfie. STill does not run. The last post I saw of someone using this successfully was Mar 26. Anyone out there using this teleprompter at the moment? Any tips?

**Comment by bradisbell** [comment]
@fmerk353 What specific issue are you getting?  What errors do you see in the console?

This is working for me as of this morning, even with the new Graph 3.0 API changes.

**Comment by bradisbell** [comment]
Closing for now, due to lack of specific feedback.  Please feel free to post again with more details on the errors you are seeing and we can re-open the issue.
