### ISSUE TITLE
Can you check for me what did i wrong?

### ISSUE THREAD

**Issue by JustSmile739** [fbsamples/live-comments-teleprompter#15]
https://monacotdien.tk/live/
THis is my website that i have deploy the code, and it just not work. Can you help me pls

**Comment by bradisbell** [comment]
What specific issue are you having?  If you're having trouble with a loading specific Facebook post URL, can you comment with what that URL is?

**Comment by JustSmile739** [comment]
Exp : https://www.facebook.com/cotdienvintage/videos/196981364287709/
i tried without https or www, nothing work, its keep saying that Your URL was not recognized. Please post a URL to a specific post on Facebook.

**Comment by bradisbell** [comment]
The URL is working fine for me.  Can you look at your browser's developer console to see if there are any errors?

![image](https://user-images.githubusercontent.com/1097509/40498239-51060806-5f33-11e8-9a69-a1cb4c01781c.png)

**Comment by JustSmile739** [comment]
I guess u wanna ask for this ?
![screen shot 2018-05-25 at 12 00 28 am](https://user-images.githubusercontent.com/12747694/40500379-b731a916-5fae-11e8-8240-2188113acce0.png)

**Comment by bradisbell** [comment]
Is your app in public mode?  If so, you have to submit it for review.  If you're using it just for yourself, leave it in dev mode for now.

**Comment by gianviterbo** [comment]
I'm also having the same issues on this link: https://gadgetpilipinas.net/live/. App is in public, and URL is set to gadgetpilipinas.net. What did I do wrong? Thank you.

**Comment by bradisbell** [comment]
@gianviterbo You didn't do anything wrong, you just need to submit your app for review if you want to use it in public mode.  The APIs that the Live Comments Teleprompter uses have become much more restrictive in recent months.  You can use them in dev mode for some things without having to go through the review.
