### ISSUE TITLE
Application request limit reached

### ISSUE THREAD

**Issue by Lortbyron** [fbsamples/live-comments-teleprompter#16]
it Works the first time , next time i try to use it  i got this messeage on the console ,
Its there any solution or it only works for certain time until it gets to its limites

![sin titulo-1](https://user-images.githubusercontent.com/7397712/41489036-0b321940-70b4-11e8-852d-1c7b2d394da6.jpg)

**Comment by bradisbell** [comment]
Unfortunately, this is the reality of current rate limits with the Facebook Graph API.  The only way to get a higher limit is to have more active users of the application.

A future modification might be to use the SSE endpoint, but the SSE endpoint only works for videos... it doesn't work for regular posts on Facebook.
