### ISSUE TITLE
from object is undefined

### ISSUE THREAD

**Issue by ayech0x2** [fbsamples/live-comments-teleprompter#2]
**jQuery.Deferred exception: Cannot read property 'name' of undefined TypeError: Cannot read property 'name' of undefined**

**Comment by bradisbell** [comment]
@ayech0x2 It looks like this might happen if a comment comes back with no `from` property.  This is unusual.  What is the ID of the comment on which this error occurs?

**Comment by bradisbell** [comment]
Please see #3.  Thanks.

**Comment by bradisbell** [comment]
v2 has been merged to master, which fully resolves this issue.  Please check it out.  Thanks.
