### ISSUE TITLE
Not displaying Info

### ISSUE THREAD

**Issue by matrixpr** [fbsamples/live-comments-teleprompter#4]
This is my error: 

An active access token must be used to query information about the current user.

**Comment by bradisbell** [comment]
Have you created an app ID and added it to the JS at https://github.com/fbsamples/live-comments-teleprompter/blob/master/js/main.js#L13?  Were you ever prompted to log in?

**Comment by matrixpr** [comment]
Hi thanks for your quick response. Yes I created and app ID and added to the JS file. Then log out of my Facebook session. Then went to try to see the url and there is no login screen prompted.

**Comment by matrixpr** [comment]
Hi , still having the issue. Can you help me set it up pls? Thanks

**Comment by bradisbell** [comment]
In the short term, clear your cookies related to Facebook and log back in again.  You should be prompted to log in.  I'm looking into the bug itself that is preventing you from seeing the login button after you've logged out.

**Comment by matrixpr** [comment]
ok will try, thanks so much for helping... will stay in touch

**Comment by matrixpr** [comment]
hi, try your recommendation but did not work.

**Comment by bradisbell** [comment]
Any errors in your developer console?

**Comment by matrixpr** [comment]
Hi found this in the web console in firefox. 

FB.NativeExtensions.onready only works when the page is rendered in a WebView of the native Facebook app. Test if this is the case calling FB.UA.nativeApp()
sdk.js:57:205
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
ping:1:51

**Comment by matrixpr** [comment]
Hello, I was able to make it work. I had to finish a step in the API configuration in the Facebook to setup login. Did this steps and worked.

https://www.nextscripts.com/instructions/facebook-social-networks-auto-poster-setup-installation/october-2017-facebook-changes/

**Comment by bradisbell** [comment]
The `FB.NativeExtensions.onready` is an SDK bug, unrelated to the issue you're having.  (More info:  https://developers.facebook.com/bugs/1514160572216577)

The real issue is that your URL isn't registered with your app ID.  The instructions you followed will solve it, but aren't quite addressing the problem.  Instead, under settings, click Basic, then Add Platform, add Website, then plug in your Site URL.  You then need to list the hostname under App Domains on the same page.

I'll leave this task open for updating the documentation to be more clear.

**Comment by matrixpr** [comment]
Hi now did , I have a personal account on facebook with a page that was created inside that personal account. I am live at my page but the script says No videos found. 
Any thoughts ?

**Comment by bradisbell** [comment]
Pages aren't covered by this version of the teleprompter. Only your personal videos are.  I recommend modifying the code to work with your page.

**Comment by matrixpr** [comment]
Thanks for your reply, I am not that expert. Any thoughts on what to change in code? or some guidelines to try?

**Comment by bradisbell** [comment]
This is the function where the ID of the video is figured out:  https://github.com/fbsamples/live-comments-teleprompter/blob/master/js/main.js#L71

If you modify that to look at your page rather than `me`, you should be able to get a different ID.  At a minimum, you could hard-code the ID here.

**Comment by matrixpr** [comment]
Hi thanks .. were exactly? function getLastLiveVideo(HERE?) {

  return fbApi(

    '/HERE?/live_videos',

    'get',

    {

      broadcast_status: ['LIVE'],

      limit: 1

    }

**Comment by bradisbell** [comment]
@matrixpr Yes, exactly.

Closing this issue, as support will be added in an upcoming version of this project.  Please 'watch' the repo for future updates.

**Comment by bradisbell** [comment]
v2 adds support for pages, and has been merged to master.  Please check it out.  Thanks.

**Comment by fmerk353** [comment]
We installed and got this running. Sent a test message and it showed up. Sent a second one and got a note from FB locking us out till we posted a selfie. STill does not run. The last post I saw of someone using this successfully was Mar 6. Anyone out there using this teleprompter at the moment? Any tips? Did FB change something with their new security policies?

**Comment by bradisbell** [comment]
@fmerk353 The teleprompter should still work in most cases.  The new Graph API changes are complex.  Please open up a new issue with your specific error message from the console, as well as specifics as to where your video is posted (group, page, your profile, etc.) and whether it's public.
