### ISSUE TITLE
webpack not running

### ISSUE THREAD

**Issue by basvcds** [fbsamples/live-comments-teleprompter#6]
When following the tutorial and running 'webpack' on osx, i get the following message:

```
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
```

So i run `npm install webpack-cli -D`, but running webpack-cli after that results in an error:
`-bash: webpack-cli: command not found
`

I do see webpack and webpack-cli sitting in the mode_modules folder, what am I doing wrong?

**Comment by bradisbell** [comment]
If you run:

```
npm install -g webpack
```

or...

```
npm install -g webpack-cli
```

Does that resolve it?

**Comment by bradisbell** [comment]
Please try `npm run build` with the fixBuildWebpackDep branch I just put up.  I think that will solve it for you.  Let me know either way, thanks.

**Comment by basvcds** [comment]
The new branch worked! Thanks a bunch!
